spring:
  profiles:
    active: dev            # 激活 dev 环境

  servlet:
    multipart:
      max-file-size: 5MB   # 单个文件最大
      max-request-size: 10MB    # 单个请求最大上传

# 配置 mybatis 规则
mybatis-plus:
  #  全局配置文件位置 不建议写，直接配置在 configuration 即可
  #  config-location: classpath:mybatis/mybatis-config.xml
  #  sql 映射文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    配置驼峰命名法
    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      id-type: auto    # 自动生成 id