server:
  port: 5000

spring:
  main:
    banner-mode: off

    datasource:
      druid:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: binn
        driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    # 开启problemdetails，启用错误处理
    problemdetails:
      enabled: true