server:
  port: 8080
spring:
  boot:
    admin:
      client:
        url: http://localhost:5000
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  appName: @project.artifactId@
  autor: bin